### ISSUE TITLE
 SA-GFLOPs计算

### ISSUE THREAD

**Issue by JasonRichard** [xianlin7/APFormer#1]
你好！非常棒的工作！
请问文中通过Query和Dependency剪枝后的SA-GFLOPs是怎么计算的呢？
我看到Util包下面有flops_counter.py这个文件，但是不太理解具体的做法。

祝好，

**Comment by xianlin7** [comment]
你好，感谢对我们工作的关注！
用flops_counter.py 中的get_model_complexity_info函数可以计算出整个模型的GFLOPs，通过提前截断模型（简单注释掉后面部分）可以得到模型任意长度的GFLOPs，简单做差就可以取出中间的SA-GFLOPs。剪枝后SA的计算复杂度可以参见论文公式16。
