### ISSUE TITLE
ISIC数据集

### ISSUE THREAD

**Issue by iaoqin** [xianlin7/APFormer#2]
作者您好，最近在复现该篇文章对于数据集的处理有些问题。
请问您是如何处理的ISIC数据集，如果可以，可以发一份到如下邮箱吗：

xiaoqin1030@webmail.hzau.edu.cn
谢谢！

**Comment by xianlin7** [comment]
数据预处理仅简单地对图像大小进行了统一，代码参见：https://paste.ubuntu.com/p/vXQwspVvdR/
