### ISSUE TITLE
About the DP

### ISSUE THREAD

**Issue by GuoQingqing** [xianlin7/APFormer#3]
Hi, you have done a splendid work and thanks for your code. I have a question about the DP.  In your paper, Equation (13) is the pruning threshold. I don't understand it. Could you please explain why the pruning threshold can be represented by this formula? 

It would be very kind of you to answer my question.
Thank you very much!

**Comment by xianlin7** [comment]
Thanks for your interest.

In our paper, the dependency pruning threshold of each query patch is adaptively adjusted according to their features.
Each query patch's dependency pruning (DP) threshold should be between the maximum and minimum dependency values. 
Therefore, equation (13) can be simplified as: min(A_pi) + a (max(A_pi) - min(A_pi)), where the adjustment factor a ∈ (0, 1).
The adjustment factor "a” is determined by the features of the corresponding query patches, i.e., f=W_t F^p_p E_qi. 
To make sure "a" ∈(0, 1), the Sigmoid function was applied on f, i.e.， f'=1/(1+e^(-f))=1/(1+e^(-W_t F^p_p E_qi)).
However, at the beginning of training, the inaccurate prediction value "f'" may lead to an excessive pruning rate, which makes the network training unstable. A learnable gate control parameter "g" is introduced to avoid that. 
To make sure "a"∈(0, 1), "g" should be modified by the Sigmoid function first, i.e., g'=1/(1+e^(-g)).
Finally, T_i = min(A_pi) + a (max(A_pi) - min(A_pi)), where a = g'f' = 1/((1+e^(-W_t F^p_p E_qi))(1+e^(-g))).

Hopefully, the above explanation helps you understand Equation(13).

**Comment by GuoQingqing** [comment]
I understand. Thank you very much for your detailed explanation.

**Comment by xianlin7** [comment]
You're welcome :)
