### ISSUE TITLE
Request your preprocessed ISIC dataset to repeat your experimentation

### ISSUE THREAD

**Issue by kk17860** [xianlin7/APFormer#4]
Could I get your preprocessed ISIC dataset? If possible, I hope to contact my Email: 513750030@qq.com. Looking forward to your reply.

**Comment by xianlin7** [comment]
Sure, I've emailed you. Please download it before it expires.

**Comment by kk17860** [comment]
Thank you very much!

**Comment by gdxujun** [comment]
您好，最近在尝试复现您的论文，请问预处理的ISIC数据集能发一份吗？我的邮箱是353858611@qq.com，非常感谢！
