### ISSUE TITLE
请求synapse数据集

### ISSUE THREAD

**Issue by cxz0101** [xianlin7/APFormer#6]
我可以得到你们预处理的synapse数据集吗？如果可能的话，我希望联系我的电子邮件：1609715968@qq.com。期待您的回复。
有三维这个数据集就更好了，谢谢您了

**Comment by xianlin7** [comment]
> 我可以得到你们预处理的synapse数据集吗？如果可能的话，我希望联系我的电子邮件：[1609715968@qq.com](mailto:1609715968@qq.com)。期待您的回复。 有三维这个数据集就更好了，谢谢您了

我们已公开预处理好的Synapse数据集，你可以通过这个链接下载：https://drive.google.com/file/d/1RxmQP_4grIdFrjwHGevPxmS5aAfVq6VP/view?usp=share_link。
