### ISSUE TITLE
About the Synapse dataset

### ISSUE THREAD

**Issue by ztt0821** [xianlin7/APFormer#7]
Hi, I found that in your training code, the Synapse dataset is preprocessed. Could you share the dataset after preprocessing? My email is ttzhang9-c@my.cityu.edu.hk

**Comment by xianlin7** [comment]
> Hi, I found that in your training code, the Synapse dataset is preprocessed. Could you share the dataset after preprocessing? My email is [ttzhang9-c@my.cityu.edu.hk](mailto:ttzhang9-c@my.cityu.edu.hk)

Hey, we have publicly released the preprocessed Synapse dataset. You can download it from the following link: https://drive.google.com/file/d/1RxmQP_4grIdFrjwHGevPxmS5aAfVq6VP/view?usp=share_link.
